<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250319074513 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE vente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_achat DATE DEFAULT NULL, recette_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_888A2A4C89312FE9 ON vente (recette_id)');
        $this->addSql('ALTER TABLE vente ADD CONSTRAINT FK_888A2A4C89312FE9 FOREIGN KEY (recette_id) REFERENCES recette (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ingredient ALTER photo TYPE BYTEA');
        $this->addSql('ALTER TABLE ingredient ALTER photo DROP NOT NULL');
        $this->addSql('ALTER TABLE ingredient ALTER assets TYPE BYTEA');
        $this->addSql('ALTER TABLE ingredient ALTER assets DROP NOT NULL');
        $this->addSql('ALTER TABLE recette ALTER photo TYPE BYTEA');
        $this->addSql('ALTER TABLE recette ALTER assets TYPE BYTEA');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE vente DROP CONSTRAINT FK_888A2A4C89312FE9');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE vente');
        $this->addSql('ALTER TABLE ingredient ALTER photo TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE ingredient ALTER photo SET NOT NULL');
        $this->addSql('ALTER TABLE ingredient ALTER assets TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE ingredient ALTER assets SET NOT NULL');
        $this->addSql('ALTER TABLE recette ALTER photo TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE recette ALTER assets TYPE VARCHAR(255)');
    }
}
